
spring.h2.console.enabled: true
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  thymeleaf:
    prefix: classpath:templates/
    suffix: .ftl
    cache: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
  format_sql: true
  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.type: trace
